### ISSUE TITLE
Cant setup without animation module :(

### ISSUE THREAD

**Issue by 231293** [scttcper/ngx-toastr#302] opened 2017-12-18 18:32 UTC
Cant setup without animation module

**Comment by scttcper** [comment] 2017-12-18 18:36
https://github.com/scttcper/ngx-toastr#setup-without-animations you follow this? You probably still need `@angular/animations` installed

**Comment by yarrgh** [comment] 2017-12-19 00:01
Yeah `@angular/animations` does need to be installed or else it errors when trying to build. Not sure exactly why though. Complains `Field 'browser' doesn't contain a valid alias configuration`

**Comment by yarrgh** [comment] 2017-12-19 16:25
By researching the error message, there seems to be a lot of different reasons to get the error: `Field 'browser' doesn't contain a valid alias configuration`, however, some suggested running `ngc` directly to get a more descriptive error.

Running `ngc` gives the following error: 
```
Error during template compile of 'Toast'
  Could not resolve @angular/animations relative to C:/Projects/test-project/node_modules/ngx-toastr/index.d.ts..
```

Even though animations aren't being used, there's still a compile time dependency to `@angular/animations`

**Comment by scttcper** [comment] 2017-12-28 23:54
has to be made into a sub bundle that doesn't mention the animations dependency. I can do it eventually

**Comment by yarrgh** [comment] 2018-01-15 19:15
We could make the default Toast component be the one without the animations and then have the Toast component with the animations be in its own module and be added/configured as an additional step.

Alternatively we could make both with and without animations be in their own separate modules and require either to be explicitly imported and configured.

**Comment by scttcper** [comment] 2018-01-15 19:18
i've found that it would have to be published almost separately or the one without animations would have to be default. The angular metadata that is emitted attempts to resolve any type dependency listed, forcing everything listed to be installed. I'm running into the same problem with https://github.com/angulartics/angulartics2 needing `@angular/router` to be installed because the base package depends on it somewhere.

**Comment by scttcper** [comment] 2018-03-22 18:36
problem ends up being with the angular metadata. https://unpkg.com/ngx-toastr@8.3.0/ngx-toastr.metadata.json

Because the default toast has `module: "@angular/animations"` it expects it to exist even if it isn't being used.

There would have to be no default toast and the toasts would have to be pulled out into their own packages/subpackages.

If we're into pulling things apart w/ no default, I'd almost rather make another toast package that starts out that way and uses angular/material2 cdk overlay+portal instead of maintaining its own. right now i think this project serves as a good continuation of `angular-toastr` that people are looking for.

**Comment by yarrgh** [comment] 2018-03-22 18:44
We could change the default toast to be without animations (included in `ngx-toastr/core`) to avoid this.

If you want animations import `ngx-toastr/animations` which would then require `@angular/animations`, and then override the default toast component in `forRoot()`.

Either way, I think looking into using `@angular/cdk` would be worth while as we're duplicating the same work that the cdk solves. Before it was necessary because it was included in the @angular/material package.

**Comment by yarrgh** [comment] 2018-06-20 16:00
Just wanted to drop in and say that this could potentially be solved when the new Ivy renderer gets released. Looks like the Ivy renderer doesn't need the `metadata.json` files anymore.

**Comment by meta72** [comment] 2018-07-19 09:02
I guess this is somehow related, due to `@angular/animations`: If I want to have a custom toast class extending Toast with its default animations, I have to copy the animations to my custom class. Otherwise I get an error:
`Error: Found the synthetic property @flyInOut. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.`
This can be reproduced by removing the animations from the `PinkToast` class in the demo app.

**Comment by scttcper** [comment] 2018-07-19 17:09
@meta72 you can extend from the `ToastNoAnimation` instead 

https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toast-noanimation.component.ts

**Comment by yarrgh** [comment] 2018-07-19 19:53
Unfortunately components can't/don't inherit animations. We could make the animations reusable to reduce boilerplate ([something like this](https://stackoverflow.com/a/39463660/1538357)), however this won't fix the issue as you still have to explicitly tell Angular what animations you want to use.

**Comment by shubhank-wynk** [comment] 2019-06-22 15:34
> @meta72 you can extend from the `ToastNoAnimation` instead
> 
> https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toast-noanimation.component.ts

Will this also imply that @angular/animations module will be included my bundle?

**Closed** 2020-10-13 03:00 UTC
