### ISSUE TITLE
Doesn't work with global options provided

### ISSUE THREAD

**Issue by brgrz** [scttcper/ngx-toastr#606] opened 2019-01-09 12:26 UTC
Works fine without options but when used like this

```
ToastrModule.forRoot({
			timeOut: 2000,
			positionClass: 'toast-bottom-right',
			preventDuplicates: true,
		}),

```

I get the following error

```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. 
Previous value: 'className: undefined'. Current value: 'className: toast-info toast'. 
It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
    at viewDebugError (core.js:18985)
    at expressionChangedAfterItHasBeenCheckedError (core.js:18973)
    at checkBindingNoChanges (core.js:19075)
    at checkNoChangesNodeInline (core.js:21946)
    at checkNoChangesNode (core.js:21935)
    at debugCheckNoChangesNode (core.js:22539)
    at debugCheckRenderNodeFn (core.js:22493)
    at Object.eval [as updateRenderer] (Toast_Host.ngfactory.js? [sm]:1)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:22482)
    at checkNoChangesView (core.js:21836)
```

**Comment by yarrgh** [comment] 2019-01-09 14:06
Duplicate of #160 

Please see that issue for a solution

**Closed by yarrgh** 2019-01-09 14:06 UTC

**Comment by brgrz** [comment] 2019-01-10 13:48
It's not a duplicate because this is related to the initialization of the global options rather than calling toastr methods from constructors or ngOnInit()
