### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by comlabmohan** [scttcper/ngx-toastr#399] opened 2018-04-06 12:20 UTC
for module D:/LocalData/z023209/str-latest/tr2/Web_Angular/app/node_modules/ngx-toastr/ngx-toastr.d.ts, found version 4, expected 3, resolving symbol AppModule 

"Could please suggest a exact toaster version for angular 4.2.4"

"dependencies": {
    "angular-devkit/schematics": "^0.5.4",
    "angular/animations": "^4.4.6",
    "angular/common": "^4.2.4",
    "angular/compiler": "^4.2.4",
    "angular/core": "^4.2.4",
    "angular/forms": "^4.2.4",
    "angular/http": "^4.2.4",
    "angular/platform-browser": "^4.2.4",
    "angular/platform-browser-dynamic": "^4.2.4",
    "angular/router": "^4.2.4",
    "ngx-translate/core": "^8.0.0",
    "ngx-translate/http-loader": "^2.0.0",
    "bootstrap": "^4.0.0-beta",
    "core-js": "^2.4.1",
    "ngx-bootstrap": "^1.9.1",
    "ngx-toastr": "^8.4.0",
    "rxjs": "^5.4.2",
    "typescript": "^2.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "angular/cli": "1.4.1",
    "angular/compiler-cli": "^4.2.4",
    "angular/language-service": "^4.2.4",
    "types/jasmine": "~2.5.53",
    "types/jasminewd2": "~2.0.2",
    "types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }

**Comment by scttcper** [comment] 2018-04-06 16:36
Duplicate of #303

**Closed by scttcper** 2018-04-06 16:36 UTC
