### ISSUE TITLE
Metadata version mismatch for module 

### ISSUE THREAD

**Issue by dharveshmydeen** [scttcper/ngx-toastr#340] opened 2018-02-14 13:13 UTC
Hi i am using it in my modle and i have installed it and it is showing the error.
Metadata version mismatch for module 

angular version : 4.4.6
ngx-toastr : 8.2.1

**Comment by scttcper** [comment] 2018-02-14 17:55
Duplicate of #303

**Closed by scttcper** 2018-02-14 17:55 UTC
