### ISSUE TITLE
How to disable hover behaviour of control

### ISSUE THREAD

**Issue by rible0** [scttcper/ngx-toastr#584] opened 2018-11-16 01:09 UTC
On a touch screen, when a button is pressed on the screen, the cursor position generally stays on the button after it has been pressed. If the button is then covered by a toastr popup, the popup is never dismissed due to the cursor hover behaviour of the control.

We need to be able to disable the hover behaviour so that the popup will dismiss even if the cursor is on top of it.

**Comment by yarrgh** [comment] 2018-12-03 18:21
Possibly a duplicate of #578 

Both are wanting a way to disable the onhover behavior.

**Closed** 2018-12-03 18:22 UTC
