### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by rsilva1959** [scttcper/ngx-toastr#309] opened 2017-12-24 13:22 UTC
ERROR in Error: Metadata version mismatch for module D:/OneDrive/.../.../.../node_modules/ngx-toastr/index.d.ts, found version 4, expected 3, resolving symbol ...

I'm using 
    angular: "^4.4.3",
    "ngx-toastr": "^8.0.0"

No errors with
    "ngx-toastr": "6.4.1-beta.0"

Pls help! Thanks.

**Comment by yarrgh** [comment] 2017-12-24 15:17
Duplicate of #303

**Closed** 2017-12-26 22:18 UTC
