### ISSUE TITLE
Error: No provider for ToastrConfig

### ISSUE THREAD

**Issue by sebichondo** [scttcper/ngx-toastr#159] opened 2017-08-09 09:13 UTC
Here is my configuration 

import { ToastrModule, ToastContainerModule } from 'ngx-toastr';

@NgModule({
    bootstrap: sharedConfig.bootstrap,
    declarations: sharedConfig.declarations,
    imports: [
        BrowserModule,
        FormsModule,
        ReactiveFormsModule,
        HttpModule,
        BrowserAnimationsModule, // required animations module
        ToastrModule.forRoot(),
        ToastContainerModule.forRoot(),
        ...sharedConfig.imports
    ],

**Comment by yarrgh** [comment] 2017-08-09 13:23
Does this happen when you try to inject ToastrConfig into a component or just whenever you try to open a toast or inject the toastrservice?

It also looks like you're using pre rendering on the server. Does this happen before or after the server side pre rendering?

**Comment by sebichondo** [comment] 2017-08-09 13:28
Yes, I have pre rendering on the server, so it happens before the server side pre rendering is completed. I noticed that the ToastrConfig was changed in the latest v6 release which meant that  if it wasn't provided in ToastrModule.forRoot(), the default configuration would suffice.

**Comment by yarrgh** [comment] 2017-08-09 13:40
The problem is that when the server tries to pre-render the page. It needs the ToastrConfig but doesn't know of the ToastrConfig (nothing is providing it for the server).

This is happening most likely because it's being provided/imported on the client module and not on the server module. You could try moving it to the shared imports and see if that helps.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yarrgh** [comment] 2017-08-21 16:04
Are you still having the issue?

**Comment by sebichondo** [comment] 2017-08-21 16:09
Hi Trevor,

Sorry for not getting back to you sooner, I was able to resolve the issue
by importing the module on the server side.

Thanks again

**Closed** 2017-08-21 16:28 UTC
